### PR TITLE
Convert to use N-API

### PR DESCRIPTION
**Pull request by librehat**
[N-API](https://nodejs.org/api/n-api.html) gives ABI stability and it is VM-agnostic (doesn't bind to V8, or a specific version of V8)

Tested with `npm test`

This conversion was done with the conversion tool provided by `node-addon-api`. Then I manually went over and fixed all compilation errors and tests issues.

### CODE REVIEW

**Comment by librehat** [comment]
Any updates? @ranisalt :smiley:

**Comment by ranisalt** [comment]
I'm having an issue with the paleolithic gcc version provided by Travis, which not only hass awfully outdated standards support but also provides useless error messages. I'll merge once I figure out what exactly is happening.

**Comment by ranisalt** [comment]
Oh boy this is glorious

**Comment by ranisalt** [comment]
Thanks a lot!

**Pull request merged**
