### PR TITLE
Prebuilt binaries with GitHub Actions

### PR DESCRIPTION
**Pull request by BjornLuG**
Hey ✋ Prebuilt binaries again :)

This time I got it to work with GitHub Actions. I removed travis too.

View the release on my fork [here](https://github.com/BjornLuG/node-argon2/releases/tag/v0.26.4).

> I've setup a new workflow described in the comment below.

### Workflow (old)
1. Run build matrix on Node 8.x, 10.x, 12.x and ubuntu-latest, macos-latest, windows-latest
2. Install dependencies (Also runs `node-pre-gyp build` after install by default)
3. Run tests
4. Build artifacts with `yarn node-pre-gyp package`
5. Upload package to release

Step 3 will run only during a push or pull request and step 4 & 5 will only run when publishing a release. This can be subjected to change as you wish.

### Minor issues
1. When I published a release, it seems to trigger a push too. So two actions: on push and on release were triggered. This won't be much of an issue but just FYI. **UPDATE**: Creating new release also pushes a new tag, causing a push event.
2. The [release-asset-action](https://github.com/csexton/release-asset-action) seems to have a [minor bug](https://github.com/csexton/release-asset-action/issues/6) currently, but I have provided a fix with `release-url: ${{ github.event.release.upload_url }}` on the last line which can be removed after the issue is fixed.
3. I didn't add the `yarn publish` command in for release since it wasn't included in the travis.yml file. Should be simple to add this step in the workflow if needed.

This should work out of the box, so I hope this gets merged since I don't want to use bcrypt. Cheers!

EDIT: I realized the gh-actions branch's action also affects the master branch. This action was also based on that branch's action, so both action have the same name `CI`. I think this workflow should replace gh-actions branch's to prevent conflict, and if so I'll add the `yarn publish` portion below?

### CODE REVIEW

**Comment by BjornLuG** [comment]
I separated push, pull request workflow and release workflow so their logic are not mixed. 

Now they are two workflows:
1. "CI" for push and pull requests. Only run tests on matrix.
2. "Release" for releases. Builds binaries on matrix (No tests).

I initially setup caching for the CI workflow but it almost doubled the execution time. It's probably caused by the caching of the binaries that were built on `yarn install` and "node-pre-gyp install --fallback-to-build".

I also initially setup `yarn publish` for the Release workflow but I was not entirely sure if it would run since I don't have a NPM token to test and would cause false negatives. But here's the snippet for publishing if you're interested:

<details>
  <summary>release.yml</summary>
  
```yml
name: Release

on:
  release:
    types: [published]

jobs:
+ publish:
+   name: Publish package
+   runs-on: ubuntu-latest
+ 
+   steps:
+   - name: Checkout
+     uses: actions/checkout@v1
+     with:
+       submodules: true
+ 
+   - name: Use Node.js 8
+     uses: actions/setup-node@v1
+     with:
+       node-version: 8
+       registry-url: https://registry.npmjs.org/
+ 
+   - name: Install dependencies
+     run: yarn install --frozen-lockfile
+ 
+   - name: Publish to NPM
+     run: yarn publish
+     env:
+       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  build:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build node-${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build artifacts
      run: yarn node-pre-gyp package

    - name: Upload to Release
      uses: csexton/release-asset-action@v2
      with:
        pattern: build/stage/**/argon2*.tar.gz
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ github.event.release.upload_url }}

```
</details>

**Comment by ranisalt** [comment]
Just drop 8.x as it EOL'd and add 13.x to the build matrix and I'll merge it.

**Comment by BjornLuG** [comment]
@ranisalt Done 👍

**Comment by ranisalt** [comment]
Thanks! You can add the publish snippet, I will provide the token to the repo.

**Comment by BjornLuG** [comment]
No problem. Added the snippet 👌

**Comment by ranisalt** [comment]
Thanks!

**Comment by ranisalt** [comment]
Now I just need to publish a new release through Github, right?

**Comment by BjornLuG** [comment]
Awesome! I think the `package.json`'s version still needs to be incremented manually. After that, create a release on GitHub and the action will run.

**Comment by BjornLuG** [comment]
Oh, and I just realized the README's badges might need to be updated too, using GitHub Action's badges.

**Comment by ranisalt** [comment]
Sweet. I just noticed that nuked coverage and quality reports for Coveralls and Codacy, if you mind taking your time to restore it would be nice.

**Comment by BjornLuG** [comment]
I dont have experience with those services, but I'l try to look into it. I'll send another PR once I figured it out

**Comment by ranisalt** [comment]
NPM requires two factor auth even with an auth token. I'm disappointed but not surprised how NPM is badly designed, the whole point of using a token is to skip 2FA.

**Comment by BjornLuG** [comment]
Well that sucks. The release workflow also odd out, but seem to publish the binaries correctly. Do you want to do npm publishing manually?

And btw, I cant seem to find any issue with Codacy. Coveralls needs another build step to send lcov results.

**Comment by ranisalt** [comment]
I just disabled 2FA for now, it worked and the releases have been published :blush:

**Pull request merged**
