### PR TITLE
`generateSalt` fix + tslint & eslint & code style

### PR DESCRIPTION
**Pull request by SamuelMarks**
Was annoyed at the removal of `generateSalt`. So I've bootstrapped it back in within the `options` of the `hash` function.

Also did minor code style changes. If you like, forget all but these two lines:

    // In `Options` interface:
    saltGeneratorF?: (size: number, callback: (err: Error, buf: Buffer) => void) => void;

    // In `hash` function
    options.saltGeneratorF == null ? crypto.randomBytes : options.saltGeneratorF

### CODE REVIEW

**Comment by ranisalt** [comment]
What is the use case of custom salt, besides testing?

**Comment by SamuelMarks** [comment]
@ranisalt: I am storing the salt in my database, which I retrieve for my default user account created on launch of my REST API server. New salts are generated for new users and not stored in database, just the regular `argon2.hash` and `argon2.verify` are used.

**Comment by ranisalt** [comment]
You know the salt is stored in the hash, right? You don't need to store it separately with Argon2.

**Comment by SamuelMarks** [comment]
Yeah I changed all my scaffolds half a day ago.

I think my original reasoning was that salting took too long, but yeah.

Anyways: close or merge!

**Comment by ranisalt** [comment]
Since we use `standard` for linting, you should revert style changes and check with `standard` instead. The PR should really be the 2 lines you point out, as the other changes are unrelated.

Also, could you open another PR with the TSLint config? It would be nice to have it.

**Comment by ranisalt** [comment]
@SamuelMarks I think I'll actually expose custom salting like you did and additionally expose the `secret` parameter as means of peppering the password too.

**Pull request closed without merging**
