### PR TITLE
Change default hash function to argon2id

### PR DESCRIPTION
**Pull request by SvenMW**
Change the default as recommended by the current IETF Draft:
https://tools.ietf.org/html/draft-irtf-cfrg-argon2-10

This fixes:
https://github.com/ranisalt/node-argon2/issues/252

### CODE REVIEW

**Comment by SvenMW** [comment]
I'm not so sure anymore about my change to the default Timecost, see the discussion here:
https://github.com/P-H-C/phc-winner-argon2/issues/271

The RFC is somewhat misleading in this regard.

**Comment by ranisalt** [comment]
khovratovich says it is the only part missing in the RFC, we could wait a little while until they update it. Or either start recommending argon2themax or provide a helper to calculate safe defaults.

**Comment by yisibl** [comment]
Can we use `Argon2id` as the default value now?

**Comment by SvenMW** [comment]
I'm currently not working in this area, feel free to adopt this change :)

**Comment by ranisalt** [comment]
Merged with [f9a386d](https://github.com/ranisalt/node-argon2/commit/f9a386d22915ac0d936d75eafceee2761d274de2)

**Pull request closed without merging**
