### PR TITLE
Disable anonymous namespace definition for Windows compilers

### LINKED ISSUE #134: TypeError: opts must be an object
### Steps to reproduce
1. run test/test.js _or_
2. execute `argon2.hash("password")`

EDIT: using node-argon2 0.19.2 and 0.19.1 the hashing doesn't work, but on 0.19.0 it does, but the verifying doesn't work there.

### Expected behaviour
1) tests are supposed to pass _or_ 2) argon2 is supposed to hash my password

### Actual behaviour
instead of passing tests or even hashing the password argon2 prints out a TypeError:
```
TypeError: opts must be an object
    at Object.serialize (node_modules\@phc\format\index.js:55:11)
    at Promise.then.then.output (node_modules\argon2\argon2.js:70:16)
    at <anonymous>
```
after debugging the code the problem occurrs by calling bindings.hash() at https://github.com/ranisalt/node-argon2/blob/master/argon2.js#L57 because of undefined err and value

### Environment
**Operating system**: Windows 10 Pro 64bit (Version 10.0.17134 Build 17134)

**Node version:** Node.js v8.11.1

**Compiler version:**
windows-build-tools@2.3.0
Microsoft Visual C++ 2017 (v. 14.14.26405.0)
Microsoft Visual C++ Build Tools (v. 14.0.25420.1)

### PR DESCRIPTION
**Pull request by mannatera**
Fixes #134

### CODE REVIEW

**Comment by jdforsythe** [comment]
Thanks @mannatera this is blocking Windows development right now.

**Comment by ranisalt** [comment]
Thanks!

Also, do you happen to know how to file this bug report to Microsoft developers?

**Comment by jdforsythe** [comment]
I'm not a C++ dev but the Visual C++ docs lead me to believe anonymous namespaces should work:

https://msdn.microsoft.com/en-us/library/5cb46ksf.aspx#anonymous%20or%20unnamed%20namespaces

**Comment by mannatera** [comment]
It might as well be a bug with Nan. When I tested it and added new NAN_METHOD which called a class that was outside the anonymous namespace leaving all other code as is (that means that HashWorker and all related classes were still under anonymous namespace) then I got it all working too, with no problems.

I cannot explain this, but it seemed that initiating class outside the namespace "fixed" the class inside the anonymous namespace also.

My best explanation is that Execute() method of Nan::AsyncWorker was called, but when it finished HandleOKCallback() was not called afterwards - leading to this bug in Windows.

**Pull request merged**
