### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by doriandevtech**

### CODE REVIEW

**Comment by ranisalt** [comment]
Thanks!

**Comment by doriandevtech** [comment]
> Thanks!

You're welcome! Do you know why the checks are failing ?

**Comment by ranisalt** [comment]
On this branch, it's because I merged it before the checks ran so when it tried to checkout the PR branch, it was already deleted.

On master, it's because SonarCloud is a PITA to configure, everytime I add the missing config I discover a new missing config.

**Comment by doriandevtech** [comment]
> On this branch, it's because I merged it before the checks ran so when it tried to checkout the PR branch, it was already deleted.
> 
> 
> 
> On master, it's because SonarCloud is a PITA to configure, everytime I add the missing config I discover a new missing config.

Ok, so did it merged my changes ? Because my PR seems to have been rejected

**Comment by ranisalt** [comment]
> Ok, so did it merged my changes ? Because my PR seems to have been rejected

It did! You may be confused because closed and merged have the same color now, but it has been merged and you can check the README.md :)

**Comment by doriandevtech** [comment]
> > Ok, so did it merged my changes ? Because my PR seems to have been rejected
> 
> 
> 
> It did! You may be confused because closed and merged have the same color now, but it has been merged and you can check the README.md :)

I was confused, not because of the color of the PR status, but because I wasn't seeing myself in the "contributors" section. But then I saw the term "code" before "contributors"... and I understood that my confusion had no reason to be 😂😂

**Pull request merged**
