### PR TITLE
Alpine builds

### LINKED ISSUE #223: Provide alpine linux compatible prebuilt binaries
I am using the argon2 module in alpine linux (in a container to be more specific). When I try to install the latest version (0.25.1) I get the following error when trying to download the prebuilt package.

```
error /app/node_modules/argon2: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /app/node_modules/argon2
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@12.10.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/app/node_modules/argon2/lib/binding/argon2.node" (not found)
node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
node-pre-gyp http 404 https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@12.10.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
```

It would be great if a musl compatible prebuilt binary would be available so I don't need to fallback to compilation.

### PR DESCRIPTION
**Pull request by Zycon42**
Resolves #223 

Builds musl compatible binary inside alpine docker image. Also tests run inside alpine too.

I configured node-pre-gyp for N-API [documentation](https://github.com/mapbox/node-pre-gyp#n-api-considerations) so now we can leverage ABI stability N-API brings and build single binary for node >= 10.0.0.

### CODE REVIEW

**Comment by ranisalt** [comment]
Isn't it possible to have a separate job running straight inside the Alpine container? That would make the action much cleaner and avoid the need for helper scripts.

**Comment by Zycon42** [comment]
Thanks, I'm new to github actions so it didn't occured to me. I deleted helper scripts and created new jobs that run in alpine container.

**Comment by ranisalt** [comment]
Looks sweet! Any reason to use node 10 instead of 12? I assume it is safe considering ABI stability though.

**Comment by Zycon42** [comment]
I observed that node 12 on windows creates binary twice as large as node 10. I have no idea why, but I tested it and binary created by node 10 works with node 12.

**Comment by ranisalt** [comment]
Summoning @hoangvvo to have a look here

**Pull request merged**
