### PR TITLE
Adding compiler instructions to readme for OSX.

### PR DESCRIPTION
**Pull request by rdegges**
References #29.

### CODE REVIEW

**Comment by ranisalt** [comment]
Hey, I just read that a gcc link to a working clang version is shipped with recent versions of Xcode. Could you try updating your Xcode version and checking if the builtin gcc works? Also post your `gcc --version` output, just for the sake.

**Comment by rdegges** [comment]
Sure --

I've got xcode updated already (that didn't appear to help), and here's my output for `gcc --version`:

```console
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

**Comment by ranisalt** [comment]
Good, I see it uses gxx 4.2.1 which is not suitable for modern C++.

**Comment by rdegges** [comment]
Thanks! Appreciate the merge <3

**Pull request merged**
