### PR TITLE
Prebuild Node and Electron binaries

### PR DESCRIPTION
**Pull request by rihardsgravis**
Add [Prebuild](https://github.com/prebuild/prebuild) for pre-building Node and Electron binaries for Linux, Windows and macOS.

Binaries are served via GitHub releases and are used on package install instead of building from source.

### CODE REVIEW

**Comment by ranisalt** [comment]
Damn, that looks sweet.

I'm unsure about not testing on older supported versions, though (that was an issue before). Also, you don't need to run `npm install` since that's the default `install` step.

**Comment by rihardsgravis** [comment]
> I'm unsure about not testing on older supported versions, though (that was an issue before). Also, you don't need to run npm install since that's the default install step.

You're right on both. Reversed those changes and bundled the `prebuild` to be triggered only when if the current build is for a git tag (no reason to run on every build).

**Comment by ranisalt** [comment]
@rihardsgravis sorry for the delay. Is this still the updated branch? I see that you have another branch named prebuild-release with more recent commits.

**Comment by Buri** [comment]
Any update on this?

**Comment by SamuelMarks** [comment]
Would be great to have this

**Comment by ranisalt** [comment]
@Buri @SamuelMarks v0.23.0 should include prebuilt binaries, please check if everything is working.

**Pull request closed without merging**
